server:
  port: 8087

spring:
  ############# Database
  data:
    mongodb:
      uri: mongodb://rodrigobeker18:XHjQFPQnu9P801Q3@ac-repgiss-shard-00-00.4gbumww.mongodb.net:27017,ac-repgiss-shard-00-01.4gbumww.mongodb.net:27017,ac-repgiss-shard-00-02.4gbumww.mongodb.net:27017/?ssl=true&replicaSet=atlas-111gmh-shard-0&authSource=admin&retryWrites=true&w=majority

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  ############# Mail
  mail:
    host: sandbox.smtp.mailtrap.io
    username: 7c20e766c0830d
    auth: LOGIN
    password: 91b91092a08425
    port: 587
    starttls:
      enable: true

  ############ JWT Properties
jwt:
  public:
    key: classpath:app.pub
  private:
      key: classpath:app.key
  expiration:
      time: 100000000
