server:
  port: 8087

spring:
  ############# Database
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/anxybrain}

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  ############# Mail
  mail:
    host: sandbox.smtp.mailtrap.io
    username: 7c20e766c0830d
    auth: LOGIN
    password: 91b91092a08425
    port: 587
    starttls:
      enable: true

  ############ JWT Properties
jwt:
  public:
    key: classpath:app.pub
  private:
      key: classpath:app.key
  expiration:
      time: 100000000
